name: Auto Build EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PySide6 pyqtgraph psutil keyboard pywin32

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --name "LightMonitor" --icon "icon.ico" --add-data "icon.png;." --add-data "icon.ico;." "main.py"

    - name: Update GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "latest-build"
        name: "LightMonitor - Latest Auto-Build"
        body: "🚀 This `.exe` is automatically compiled by GitHub Servers every time new code is pushed to the repository. No manual build required!"
        files: dist/LightMonitor.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
